# -*- coding: utf-8 -*-
"""train-hifigan-v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13nk5V7DREVAeML9Q6nsHueQlUC6m6Ssq

# SCE-TTS: HiFi-GAN 학습

이 문서는 SCE-TTS 프로젝트의 HiFi-GAN 학습용 문서입니다.

이 데모에 대한 더 자세한 정보는 아래 링크에서 확인하실 수 있습니다.  
https://sce-tts.github.io/

실제 학습을 진행하시려면, 위쪽 메뉴에서 `런타임 -> 모두 실행`을 클릭하신 후,  
문서 최하단의 `HiFi-GAN 학습 진행`까지 정상적으로 실행되는걸 확인해주시면 됩니다.

도중에 문제가 발생한다면, 문제의 원인을 해결한 후 `런타임 -> 런타임 초기화`를 클릭하고,  
다시 `런타임 -> 모두 실행`을 클릭해주세요.

## 1. 할당된 GPU 확인

현재 런타임에 할당된 GPU를 확인합니다.

만약, `GPU: NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.` 라는 메시지가 출력된다면, 위쪽 메뉴에서 `런타임 -> 런타임 유형 변경`을 클릭하고 하드웨어 가속기를 `GPU`로 변경하여 저장한 후 다시 실행해주세요.
"""

import os
GPU_NAME = os.popen('nvidia-smi --query-gpu=name --format=csv,noheader').read().strip()
os.environ['GPU_NAME'] = GPU_NAME
print(f'GPU: {GPU_NAME}')

"""## 2. 구글 드라이브 마운트

음성합성을 위해 학습한 모델이 있는 구글 드라이브를 마운트합니다.  
마운트할 구글 드라이브 내에 다음 파일이 존재하는지 꼭 확인해주세요.

- `/Colab Notebooks/data/filelists.zip`

(존재하지 않는다면, [음성 데이터셋 변환](https://sce-tts.github.io/#/recoding?id=%EC%9D%8C%EC%84%B1-%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%85%8B-%EB%B3%80%ED%99%98)문서를 참조하여 준비해주세요.)

만약 아래에 `Enter your authorization code:`과 같은 메시지가 출력될 경우,  
같이 출력된 링크에 접속하여, 마운트할 구글 계정을 선택하신 후, 인증 코드를 복사하여 입력해주세요.
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!apt-get update
!apt-get install -y python3.8 python3.8-dev python3.8-venv
!python3.8 -m venv tts_env
!tts_env/bin/pip install --upgrade pip
!git clone --depth 1 https://github.com/sce-tts/TTS.git -b sce-tts
# %cd /content/TTS
!/content/tts_env/bin/python setup.py develop

!/content/tts_env/bin/pip install numpy torch scipy

"""## 3. 필수 라이브러리 및 함수 불러오기

실행에 필요한 라이브러리 및 함수를 불러옵니다.

이 과정은 약 10분 정도 소요될 수 있습니다.
"""

import sys
from pathlib import Path

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!rm -rf TTS  # 기존 TTS 디렉토리 삭제
!git clone --depth 1 https://github.com/sce-tts/TTS.git -b sce-tts
# %cd /content/TTS
!/content/tts_env/bin/pip install --upgrade pip
!/content/tts_env/bin/pip install numpy torch scipy  # 필수 의존성 설치
!/content/tts_env/bin/pip install -r requirements.txt  # requirements.txt가 있으면 실행
!/content/tts_env/bin/python setup.py develop

"""## 4. 학습할 데이터셋 불러오기

학습에 사용할 음성 데이터를 구글 드라이브에서 가져옵니다.
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/TTS
!cp "/content/drive/My Drive/Colab Notebooks/data/filelists.zip" ./filelists.zip
!rm -rf ./filelists
!unzip -q filelists.zip -d ./filelists

"""## 5. 사전 학습 데이터 불러오기

사전 학습 데이터가 구글 드라이브에 존재하지 않을 경우,  
SleepingCE Speech Dataset의 사전 학습 데이터를 내려받습니다.
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/TTS
!mkdir -p "/content/drive/My Drive/Colab Notebooks/data/hifigan-v2"
if not Path("/content/drive/My Drive/Colab Notebooks/data/hifigan-v2/config.json").exists():
    !gdown --id 1vRxp1RH-U7gSzWgyxnKY4h_7pB3tjPmU -O hifigan-v2.zip
    !unzip -q hifigan-v2.zip -d ./
    !cp -R ./hifigan-v2/* "/content/drive/My Drive/Colab Notebooks/data/hifigan-v2/"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/TTS
from pathlib import Path

# 통계 파일 생성
if not Path("/content/drive/My Drive/Colab Notebooks/data/hifigan-v2/scale_stats_new.npy").exists():
    !/content/tts_env/bin/python TTS/bin/compute_statistics.py \
        "/content/drive/My Drive/Colab Notebooks/data/hifigan-v2/config.json" \
        "/content/drive/My Drive/Colab Notebooks/data/hifigan-v2/scale_stats_new.npy" \
        --data_path "/content/TTS/filelists/wavs/"

"""## 6. TensorBoard 실행

학습 진행을 확인하기 위해 TensorBoard를 실행합니다.

최신 학습 진행 상황을 확인하려면 TensorBoard 우측 상단의 새로고침 아이콘을 클릭해주세요.
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir="/content/drive/My Drive/Colab Notebooks/data/hifigan-v2"

"""## 7. HiFi-GAN 학습 진행

실제 HiFi-GAN 학습을 진행합니다.

학습이 정상적으로 진행되면, 이 셀은 종료되지 않고 계속 실행되는 상태를 유지합니다.

학습 진행 정도를 시각적으로 확인하시려면 바로 위의 TensorBoard를 참고해주세요.

학습된 결과를 확인하고 싶으시다면, 가장 최근 체크포인트를 [SCE-TTS: 음성합성 데모](https://colab.research.google.com/drive/1YkxjzBz3V4eXoAaEgcFNEUg8ZyWV40x9)에서 불러와 확인할 수 있습니다.

처음 학습을 수행할 때에는 아래 셀을 그대로 실행하면 됩니다.

이전에 학습을 진행하던 모델을 이어서 학습을 진행하시려면 다음과 같이 수정한 후 실행해주세요.

- 아래 셀에서 2 ~ 3번째 줄의 코드를 주석을 해제합니다.
- 3번째 줄의 경로를 이어서 학습을 진행할 모델의 경로로 변경합니다.  
(예시: `/content/drive/My Drive/Colab Notebooks/data/hifigan-v2/hifigan-v2-May-31-2021_08+26AM-d897f2e`)
- 4번째 줄 아래의 코드를 제거합니다.
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/TTS
from pathlib import Path

!/content/tts_env/bin/python TTS/bin/train_vocoder_gan.py \
    --config_path "/content/drive/My Drive/Colab Notebooks/data/hifigan-v2/config.json" \
    --coqpit.data_path "/content/TTS/filelists/wavs" \
    --coqpit.audio.stats_path "/content/drive/My Drive/Colab Notebooks/data/hifigan-v2/scale_stats_new.npy" \
    --coqpit.output_path "/content/drive/My Drive/Colab Notebooks/data/hifigan-v2/" \
    --coqpit.num_loader_workers 2 \
    --coqpit.num_val_loader_workers 2 \
    --restore_path "/content/drive/My Drive/Colab Notebooks/data/hifigan-v2/model_file.pth.tar"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/TTS
# !(python TTS/bin/train_vocoder_gan.py \
#     --continue_path "/content/drive/My Drive/Colab Notebooks/data/hifigan-v2/CONTINUE_DIRECTORY")
!(python TTS/bin/train_vocoder_gan.py \
    --config_path "/content/drive/My Drive/Colab Notebooks/data/hifigan-v2/config.json" \
    --coqpit.data_path "/content/TTS/filelists/wavs"  \
    --coqpit.audio.stats_path "/content/drive/My Drive/Colab Notebooks/data/hifigan-v2/scale_stats_new.npy"  \
    --coqpit.output_path "/content/drive/My Drive/Colab Notebooks/data/hifigan-v2/"  \
    --coqpit.num_loader_workers 2  \
    --coqpit.num_val_loader_workers 2  \
    --restore_path "/content/drive/My Drive/Colab Notebooks/data/hifigan-v2/model_file.pth.tar")